version: "3.3"
services:
  ldap:
    image: dinkel/openldap
    volumes:
      - ./ldap.ldif:/etc/ldap.dist/prepopulate/kubi.ldif
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
    environment:
      SLAPD_PASSWORD: password
      SLAPD_DOMAIN: kubi.cagip.github.com
      SLAPD_ADDITIONAL_MODULES: memberof
      SLAPD_CONFIG_PASSWORD: config
