name: goreleaser

on:
  push:
    branches:
      - 'main'

jobs:
  docker-release:
    name: Release docker image to registries
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}       
      - name: Push to Docker Hub registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cagip/kubi-members:latest
